knp_paginator:
  default_options:
    distinct: false
    page_out_of_range: fix
  template:
    pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
    sortable: '@KnpPaginator/Pagination/bootstrap_v5_bi_sortable_link.html.twig'
    filtration: '@KnpPaginator/Pagination/bootstrap_v5_filtration.html.twig'