import { generateElements, fadeIn, fadeOut, addEventListener } from "utils/dom";

const DELAY = 5000;

function getFlashContainer(): HTMLElement {
    const flashMessagesContainer = document.querySelector('.flash-messages-container');
    if (!flashMessagesContainer) {
        throw new Error('Flash container not found');
    }
    
    return flashMessagesContainer as HTMLElement;
}

export enum FlashMessageType {
    SUCCESS = 'success',
    WARNING = 'warning',
    ERROR = 'danger',
}

/**
 * Allows the creation of flash messages asynchronously.
 */
export class FlashMessage {
    message: string;
    type: FlashMessageType;
    element: HTMLElement; 

    constructor(message: string, type: FlashMessageType = FlashMessageType.SUCCESS) {
        if (Array.isArray(message)) {
            this.message = message[0].message;
        } else {
            this.message = message;
        }
        this.type = type;
        this.element = this.generateMessage();
    }

    generateMessage() {
        this.element = generateElements(`
            <div class="flash-message alert alert-${this.type} mb-0 p-3 hide"> 
                <p>${this.message}</p>
            </div>
        `);
        getFlashContainer().append(this.element);
        requestAnimationFrame(() => fadeIn(this.element));

        addEventListener(this.element, 'click', () => fadeOut(this.element));

        setTimeout(() => fadeOut(this.element), DELAY);

        return this.element;
    }
}

/**
 * Displays the flash message generated by kyManager.js.
 */
const StoredFlashMessage = localStorage.getItem('flashMessage');
if (StoredFlashMessage) {
    const { message, type } = JSON.parse(StoredFlashMessage);
    new FlashMessage(message, type);
    localStorage.removeItem('flashMessage');
}

/**
 * Displays all flash messages that come from PHP code.
 */
for (const child of getFlashContainer().children) {
    const flashText = child.textContent;
    const className = child.className;
    const match = className.match(/alert-([\w-]+)/)!; // Can't be null : Symfony flash message can't be instanciated without type and alerts are normalized in base.html.twig.
    child.remove();
    new FlashMessage(flashText, match[1] as FlashMessageType);
}